### ISSUE TITLE
Error boundaries should implement getDerivedStateFromError()

### ISSUE THREAD

**Issue by danielkcz** [WebCloud/react-error-reporter#2]
This a new warning coming from freshly released React 16.6.

> Warning: ErrorBoundaryComponent: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.

I am not sure how it should work just yet, but I suppose it should be adapted to this.

**Comment by WebCloud** [comment]
Well noted. I'll publish a patch soon. Thanks for the headsup
