### ISSUE TITLE
Any way to alter CSS specially in production mode?

### ISSUE THREAD

**Issue by dehghani-mehdi** [WebCloud/react-error-reporter#4]
Hey,

You did great job with default CSS, I'm wondering is there any way to alter or even disable default CSS, specially in production mode?

Thanks.

**Comment by WebCloud** [comment]
You would have to use the `errorMessageComponent` prop to pass a new component to be rendered for the styles are inlined.

**Comment by dehghani-mehdi** [comment]
I saw that in README, but you wrap provided HTML with a div with some inline styles, by altering the css I mean that inline styles.

**Comment by WebCloud** [comment]
I see. That is not supported now. But for the next version it will be, or once provided the custom component it won't have any wrapping styles, so it does not interfere with wherever it is integrated. Thanks for the feedback.
